### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by egeste** [cballou/Turntable.FM-Squared#1]
I just wanted to say, this is a super cool project and I really like what you're doing here. Feel free to snag any code you find useful from ttTools

**Comment by cballou** [comment]
Thanks, it's really been a work in progress for the last 6 or so months and I finally felt as though it was in a spot worth sharing.
- Corey

**Comment by cballou** [comment]
I will say that I've really been interested in implementing a form of playlist management which you've build out with tagging and filtering. Would you be cool if I did some integration with your ttTools work? I think it's one of the major features that I'm lacking in terms of a full user experience on TT.FM.

**Comment by egeste** [comment]
Sure, but I would ask that you wait until I upgrade the tagging system - I'm going to switch to a new ,api-based tag storage solution with node running on tttools.egeste.net - I invite you to use my code and hook into my api server once it's up and running

**Comment by cballou** [comment]
Yeah, I'd definitely be interested in working with an API based system that you're cooking up. That'd be some awesome stats server side; got plans for the collected dataset? If you need help, I'd be willing to aid in getting it production ready with you.

**Comment by egeste** [comment]
We should talk offline - add me on gchat: egeste@egeste.net
