### ISSUE TITLE
User list popup issues

### ISSUE THREAD

**Issue by Xenocide122** [cballou/Turntable.FM-Squared#11]
The little popup list on the user list does not work for users that have any color but white (like red, green..) no workie..

**Comment by cballou** [comment]
Yeah, I've noticed that shifting them to the top has caused some binding problems. I managed to click rapidly and hit the button, but definitely not the proper solution. I'll look into this one!

**Comment by cballou** [comment]
Boom, fixed. I was using DOMNodeInserted, but it was being triggered by simply shuffling around the DJs and admins. It was essentially causing an endless loop, so I just had to add a check against their special classes. Hopefully this doesn't cause any other edge cases to crop up!

**Comment by Xenocide122** [comment]
Nice! Will test it out today!
