### ISSUE TITLE
%20 in Similar Tracks Search

### ISSUE THREAD

**Issue by bdhanks** [cballou/Turntable.FM-Squared#17]
When clicking on Find Similar Tracks and then clicking on the Blue Search TT.FM button you get a search string with %20 instead of the spaces that should be there.  I understand %20 is code for "space" but this causes the search results to return nothing.  An extension that seems to do this correctly is TurnTable Extended when you click on the Suggestion Link above your queue.

I don't mean to sound super critical but I'm surprised that there isn't already an open bug for this.  I saw it within minutes of installing the app and it's actually a deal breaker for me.  I love Turntable.FM-Squared more than any other extension.

**Comment by cballou** [comment]
Hey, sorry about this one bdhanks. I fixed the problem for you. If you're the negative reviewer on the appstore, hopefully this fixes your qualms with the app.

**Comment by bdhanks** [comment]
Thank you for the fix.  I'll check it out and update my review.  I don't think I'm the negative reviewer but I did give it less than a perfect review so I'll change that now!

-Brian
