### ISSUE TITLE
Settings Not Saving

### ISSUE THREAD

**Issue by brttwrd** [cballou/Turntable.FM-Squared#3]
Every time the page has to load (leaving room, refreshing, etc) the settings are reset to default, except for the text areas. So any check boxes, like auto up vote and anti idle, both of which i don't use, are enabled. Sorta gets annoying, and im getting close to getting banned sometimes when i meant to have auto DJ off.

**Comment by brttwrd** [comment]
If you need my logs or anything, email me: brttwrd@gmail.com

**Comment by cballou** [comment]
Thanks for the report. Currently, the settings are being saved via a localStorage solution. If you're noticing any console errors, I'd definitely like to see. I'll send you an email.

**Comment by SarekOfVulcan** [comment]
Same issue here, I think -- when I click on "Save Settings", nothing appears to happen.

**Comment by cballou** [comment]
This looked like it was specific to auto upvote. Perhaps anti idle was fixed awhile back and I forgot to comment. I fixed the auto upvote save bug, but the rest of the fields appear to be saving fine. 

@SarekOfVulcan in terms of save settings, it happens automatically, so perhaps I'll just add in a message indicating things have been saved properly :)

Let me know if you find any others!
