### ISSUE TITLE
The auto upvote stops all the time

### ISSUE THREAD

**Issue by ctely515** [cballou/Turntable.FM-Squared#4]
I have to either press awesome myself to "reset" it or I have to uncheck, save settings, check it again, save settings. This is a great extension, just have this issue with it lol. Hope you can fix it!!

**Comment by cballou** [comment]
Thanks for the bug report! I've sadly noticed this myself the last week or so... It appears as though TT.FM has changed their API handling for voting, so I'll be looking to incorporate code from Izzmo's Auto-Upvote plugin in the next few days when I get some spare time. Hold tight!

**Comment by cballou** [comment]
I switched to Izzmo's auto upvote handling using sockets and it appears as though this issue has gone away. You'll need to upgrade to version 1.1.0 of the chrome extension (not sure if it does this automatically or not). I'll have to add a version number to the tooltip from now on.
