### ISSUE TITLE
Stats seem like they are not doing much...

### ISSUE THREAD

**Issue by Xenocide122** [cballou/Turntable.FM-Squared#6]
Yea they really never changed at all for me.

**Comment by cballou** [comment]
Do you know if you're getting any kind of errors in your Developer Toolbar or Firebug? Also, how do you have the app installed? Is it via the official Chrome extension from the store, custom chrome app install, or Firefox Greasemonkey script?

Thanks,
Corey

**Comment by Xenocide122** [comment]
I installed the app using the chrome store page... I will take a look and see if i have any errors, a friend of mine had the same issue and pointed it out to me.

**Comment by Xenocide122** [comment]
Here are the errors i am currently seeing in the console but my auto upvote is also not working as stated in a new issue i just started.

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Performing vote updating actions.

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Send notification called.

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Performing vote updating actions.

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Send notification called.

http://d3volxspmrf6x8.cloudfront.net/4e81d42914169c3ba8e24f20Seg1333977612
Failed to load resource: the server responded with a status of 418 (Unknown)

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Performing vote updating actions.

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Send notification called.

http://d3volxspmrf6x8.cloudfront.net/4e81d42914169c3ba8e24f20Seg1333977840
Failed to load resource: the server responded with a status of 418 (Unknown)

http://d3volxspmrf6x8.cloudfront.net/4e81d42914169c3ba8e24f20Seg1333977840
Failed to load resource: the server responded with a status of 418 (Unknown)

raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js:1914
Performing vote updating actions.

**Comment by Xenocide122** [comment]
Just got his error as well:

4e81d42914169c3ba8e24f20Seg1333978275:1
GET http://d3volxspmrf6x8.cloudfront.net/4e81d42914169c3ba8e24f20Seg1333978275 418 (Unknown)

**Comment by cballou** [comment]
Stats should be fixed now. I had a call that was failing and wasn't triggering any of the increment code.
